id: D146D9993
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:22:00+00:00'
last_modified: '2022-05-26T11:37:53.647707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    75c1:
      image_group_id: I1PD95872
      title: དུག་ལྔ་སྦས་པའི་ལམ་མཆོག་ཏུ་གསང་བ་བསམ་གྱིས་མི་ཁྱབ་པ།
      total_pages: 1953
      order: 27
      base_file: 75c1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
