id: c94693cb6c524fb1b92cee928de2c456
initial_creation_type: ocr
source_metadata:
  volumes:
    2156c8a9caa04de49683169050afe7a7:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: དུག་ལྔ་སྦས་པའི་ལམ་མཆོག་ཏུ་གསང་བ་བསམ་གྱིས་མི་ཁྱབ་པ།
      total_pages: 1953
      volume_number: 27
